// prettier.config.js
module.exports = {
  tabWidth: 2,
  useTabs: false,
  printWidth: 125,
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  singleAttributePerLine: false,
  bracketSameLine: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'es5',
  embeddedLanguageFormatting: 'auto',
  vueIndentScriptAndStyle: false,
  plugins: ['prettier-plugin-tailwindcss'],
};
